"""文件上传增加文件原本的创建和修改时间

Revision ID: 26278111e923
Revises: a065827f390a
Create Date: 2025-12-21 19:10:42.095713

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26278111e923"
down_revision: Union[str, Sequence[str], None] = "a065827f390a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("original_created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "files", sa.Column("original_updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("files", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "updated_at")
    op.drop_column("files", "original_updated_at")
    op.drop_column("files", "original_created_at")
    # ### end Alembic commands ###
