"""add file_type columns

Revision ID: ebae89491d40
Revises: 26278111e923
Create Date: 2025-12-28 14:17:50.181495

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebae89491d40"
down_revision: Union[str, Sequence[str], None] = "26278111e923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("file_type", sa.String(), nullable=True))
    op.add_column(
        "files", sa.Column("file_type_confidence", sa.String(), nullable=True)
    )
    op.create_index(op.f("ix_files_file_type"), "files", ["file_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_file_type"), table_name="files")
    op.drop_column("files", "file_type_confidence")
    op.drop_column("files", "file_type")
    # ### end Alembic commands ###
